### PR TITLE
Add field attributes

### PR DESCRIPTION
**Pull request by dillingham**
This will allow for some edge cases to add html attributes to the fields

For instance, I only have the repeater on update forms (hideWhenCreating)
So I don't want the questions editable
But when creating can have an infinite number of questions

```php
Repeater::make('Answers')->onlyOnForms()
    ->addField(['label' => 'Question', 'attributes' => ['readonly' => true]])
    ->addField(['label' => 'Answer']),
```
but would also allow for `required`, `max` or even `style`

```php
Repeater::make('Answers')->onlyOnForms()
    ->addField(['label' => 'Question', 'attributes' => ['style' => 'background: red;']])
    ->addField(['label' => 'Answer']),
```

### CODE REVIEW

**Comment by fourstacks** [comment]
@dillingham Thanks for the PR!  Looks great on first glance and tackles issues like the one in #12.

Bit tied up today but will pull this down tomorrow and have a quick test and merge it in over the weekend.

**Comment by dillingham** [comment]
Any update on this? :)

**Comment by dillingham** [comment]
@fourstacks ping

**Comment by michaelradionov** [comment]
Nice PR

**Comment by michaelradionov** [comment]
No, sorry, changed my mind about this PR. File changes are kinda dirty, there is absolute local path and minified stuff. @dillingham, it needs some cosmetics IMHO

**Comment by michaelradionov** [comment]
Hm, I can't find the way to PR something to this package without pushing minified files. So, on that thing, I was wrong, but I still think that absolute local path in repo is bad. @dillingham

**Comment by dillingham** [comment]
@michaelradionov

Yeah was something weird I had to do to compile properly, I will fix. Thanks

**Comment by fourstacks** [comment]
@dillingham Apologies for very slow followup - just to let you know that I implemented the code in your PR in v1.2.0 (and gave you due props).  Thanks again for taking the time to submit this

**Pull request closed without merging**
